isrubyfastyet.com/config/routes.rb
IsRubyFastYet::Application.routes.draw do

  resources :benchmarks do
    resources :results
  end

  root :to => 'content#home'
  get 'latest.log' => 'content#latest_log'

end

isrubyfastyet.com/app/models/benchmark_result_set.rb
require Rails.root.join('../shared_models/benchmark_result_set')

BenchmarkResultSet.results_dir = Rails.root.join('../results')

isrubyfastyet.com/app/models/ruby_benchmark.rb
class RubyBenchmark
  def self.from_param(param)
    result_set = BenchmarkResultSet.all.find { |result_set| result_set.name == param }
    new(result_set) if result_set
  end

  attr_accessor :result_set

  def initialize(result_set=nil)
    @result_set = result_set
  end

  def name
    param.titleize
  end

  def param
    result_set.name
  end

  def units
    all_results.find { |result| result.success? }.try(:units)
  end

  def passing_results
    all_results.select(&:success?)
  end

  def method_missing(method, *args)
    if result_set.respond_to?(method)
      result_set.send(method)
    else
      super
    end
  end
end

isrubyfastyet.com/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter { headers['Cache-Control'] = 'public'; headers['Expires'] = 1.day.from_now.httpdate } if Rails.env.production?
end

isrubyfastyet.com/app/controllers/benchmarks_controller.rb
class BenchmarksController < ApplicationController
  respond_to :json

  def index
    @benchmarks = BenchmarkResultSet.all
  end
end

isrubyfastyet.com/app/controllers/content_controller.rb
class ContentController < ApplicationController

  def home
  end

  def latest_log
    render 'latest.log', :layout => false
    headers['Content-Type'] = 'text/plain'
  end

end

isrubyfastyet.com/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  respond_to :json

  def index
    @benchmark = RubyBenchmark.from_param(params[:benchmark_id])
    @results = @benchmark.passing_results
  end
end

isrubyfastyet.com/app/helpers/application_helper.rb
module ApplicationHelper
end

isrubyfastyet.com/app/views/benchmarks/_graph.html.erb
<%
  default_time_range ||= nil

  time_range_to_start_date = {
    '1w'  =>    7.days.ago.to_date,
    '2w'  =>   14.days.ago.to_date,
    '1m'  =>   30.days.ago.to_date,
    '3m'  =>   90.days.ago.to_date,
    '6m'  =>  180.days.ago.to_date,
    'YTD' => Date.current.beginning_of_year,
    '1y'  =>    1.year.ago.to_date,
    '2y'  =>    2.years.ago.to_date,
    '3y'  =>    3.years.ago.to_date,
    '4y'  =>    4.years.ago.to_date,
  }

  default_start_date = time_range_to_start_date[default_time_range]
  graph_id           = "#{benchmark}-graph"
  graph_selector     = "#" + graph_id

  @benchmark = RubyBenchmark.from_param(benchmark)

  oldest_result_time = @benchmark.oldest_result_time
  done = false
  time_range_to_start_date = time_range_to_start_date.select do |time_range, start_date|
    next(false) if done
    done = true if oldest_result_time > start_date
    true
  end

%>

<div class="benchmark-graph-wrapper">
  <h2><%= benchmark.gsub('_', ' ').titleize %></h2>
  <p><%= raw explanation %></p>

  <div class="benchmark-graph" id="<%= graph_id %>" data-graph-benchmark="<%= benchmark %>"></div>
  <div class="benchmark-graph-legend">
  	<div class="legend"></div>
  	<div class="below-legend">Click on a Ruby above to show/hide it.</div>
  </div>

  <ul class="benchmark-graph-time-range-picker">
    <% time_range_to_start_date.each do |time_range, start_date| %>
      <li><%= link_to time_range, benchmark_results_path(benchmark, :format => :json), :data => { :"on-click-load-graph" => graph_selector, :"graph-start-time" => start_date.strftime('%Y-%m-%d') } %></li>
    <% end %>
  </ul>
  <script>
    // inline the default results for faster page loads
    <% self.lookup_context.formats = [:json] %>
    <% @results = @benchmark.passing_results.select { |result| default_start_date.to_time.utc <= result.time } %>

    $(function () {
      var default_results =
        <%= TemplateRenderer.new(self.lookup_context).render(self, :file => 'results/index').html_safe %>;
      $("<%= graph_selector %>").drawBenchmarkGraphFromJSON(default_results);
    });

    <% self.lookup_context.formats = [:html] %>
  </script>
</div>

isrubyfastyet.com/app/views/content/home.html.erb
<h1>Is Ruby Fast Yet?</h1>

<p>Practical, comparative benchmarks of Ruby implementations. Thanks to <%= link_to "RVM", "https://rvm.io/" %> for Ruby setup and compiling. <%= link_to "Github", "https://github.com/brianhempel/isrubyfastyet" %></p>

<section id="graphs">
  <%= render 'benchmarks/graph', :benchmark => 'rails_requests_per_second_steady_state', :default_time_range => '1m', :explanation => "More is better. Single-threaded; warm JIT (warmup requires around 50,000 requests for JRuby and RBX)." %>
  <%= render 'benchmarks/graph', :benchmark => 'rails_requests_per_second',              :default_time_range => '1m', :explanation => "More is better. Single-threaded; cold start (3 seconds of warmup, 15 seconds of testing)." %>
  <%= render 'benchmarks/graph', :benchmark => 'rails_startup_time',                     :default_time_range => '1m', :explanation => "Less is better. Note that JRuby does not use <a href=\"https://github.com/jruby/jruby/wiki/Improving-startup-time#try-using-theine-for-rails-apps\">Drip, Nailgun, or Theine</a> for this benchmark." %>
  <%= render 'benchmarks/graph', :benchmark => 'rails_memory_usage',                     :default_time_range => '1m', :explanation => "Less is better, if you have reason to care about memory usage." %>
</section>

<section id="so-is-ruby-fast-yet">
  <h3>So, Is Ruby Fast Yet?</h3>
  <p>
    I like to think that "fast" is, somewhat arbitrarily, either five times or ten times faster than Ruby 1.8.7. Both 5x and 10x better than 1.8.7 are significant milestones, but neither has been reached. So, no. Ruby is not fast yet.
  </p>
  <p>
    Ruby is, however, getting faster with each release. These benchmarks give a good indication of how much faster.
  </p>
</section>

<section id="about">
  <h3>About the Benchmarks</h3>
  <p>
    This is intended as a Ruby benchmark rather than a Rails one; <%= link_to "Rails", 'http://rubyonrails.org/' %> just happens to be the best thing out there to benchmark. Rails presents the greatest challenge to Ruby implementations.
  </p>
  <p>
    As a Ruby benchmark, the Rails version is locked to 3.1.3 and the server is WEBrick.
  </p>
  <p>
    I would love to compare Ruby to other dynamic languages. However, I don't know of any sufficiently complex, real-world applications that are also cross-language. If you discover any, please <%= link_to "let me know", 'https://github.com/brianhempel/isrubyfastyet/issues' %>.
  </p>
</section>

<section id="hardware">
  <h3>Hardware</h3>
  <p>
    Mid-2007 MacBook Pro<br>
    2.2GHz Core 2 Duo<br>
    6GB 667MHz DDR2 SDRAM<br>
    WD Scorpio Black 7200RPM 320GB Hard Drive<br>
    Ubuntu Server 14.04<br>
    Fans preemptively sped up with macfanctld.
  </p>
</section>

<section id="debugging">
  <h3>Debugging</h3>
  <p>
  	Is your favorite Ruby implementation not showing up? Check the <%= link_to "latest nightly log", 'latest.log' %> to learn why.
  </p>
</section>

<section id="updates">
  <h3>Updates</h3>
  <p>
    <ol>
      <li>
        <span class="date">2014-12-26</span>
        OS Switched to Ubuntu Server 14.04 from Mac OS X 10.6. JRuby is now run in OpenJDK 7. (The upgrade was required becasuse newer rubies no longer compiled on Mac OS X 10.6, and upgrading to Yosemite introduced a hard-to-diagnose performance regression that may have been in the network stack. Ubuntu shows some weird regressions in the newer MRIs, but at least runs the reference Ruby (MRI 1.8.7) at the same speed as before. Additionally, many people use Ubuntu 14.04 in production.)
      <li>
        <span class="date">2014-09-21</span>
        Older head rubies are no longer benchmarked: 1.9.2-head, 1.9.3-head, and 2.0.0-head. Note that RVM 1.8.7 actually builds 1.8.7-head for security reasons.
        Ruby uses a more semantic versioning scheme as of 2.1.0, so 2.1.0 and 2.1.0-head have been replaced by 2.1 and 2.1-head.
      </li>
      <li>
        <span class="date">2014-01-02</span>
        Java updated from 1.6.0_51-b11-457 to 1.7.0_45.
      </li>
      <li>
        <span class="date">2013-05-24</span>
        Rails Requests Per Second Steady State benchmark added to show JIT performance.
      </li>
      <li>
        <span class="date">2012-01-12</span>
        First results.
      </li>
    </ol>
  </p>
</section>

isrubyfastyet.com/app/views/content/latest.log.erb
<%
	log_path = Rails.root.join('../nightly/nightly.log')
	first_byte = `grep -b 'nightly benchmark suite start' #{log_path} | tail -1`[/^\d+/].to_i
	@latest_run = `tail -c +#{first_byte} #{log_path}`
%>

<%= raw @latest_run %>

isrubyfastyet.com/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Is Ruby Fast Yet?</title>
  <link href='http://fonts.googleapis.com/css?family=Peralta|Source+Sans+Pro:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="body-wrapper">
    <%= yield %>
  </div>

  <% if Rails.env.production? %>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-37395032-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  <% end %>

</body>
</html>