runner/benchmarks/rails/config/routes.rb
RailsBenchmarks::Application.routes.draw do
  devise_for :users

  resources :listings do
    resources :bids
  end

  resource :pid, :only => :show

  root :to => "listings#index"

end

runner/benchmarks/rails/app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing
  
  validates :amount, :presence => true, :numericality => true
  validate :verify_minimum_bid
  
  def verify_minimum_bid
    if amount && listing.highest_bid && listing.highest_bid.amount >= amount
      errors.add :amount, 'must be higher than the highest bid.'
    end
  end
  
  def to_s
    amount
  end
end

runner/benchmarks/rails/app/models/listing.rb
class Listing < ActiveRecord::Base
  validates :title, :presence => true
  # validates :title, :format => {:with => /^[A-Z]/, 
  #             :message => 'must begin with a capital letter'}
  # validates :description, :presence => true
  
  belongs_to :user
  has_many :bids
  
  mount_uploader :image, ImageUploader
  
  def highest_bid
    bids.order('amount DESC').first
  end
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
end

runner/benchmarks/rails/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :listings
  has_many :bids
end

runner/benchmarks/rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

runner/benchmarks/rails/app/controllers/bids_controller.rb
class BidsController < ApplicationController
  
  before_filter :authenticate_user!
  
  def create
    @listing = Listing.find(params[:listing_id])
    @bid = @listing.bids.build(params[:bid])
    @bid.user = current_user
    if @bid.save
      BidMailer.bid_notification(@bid).deliver
      respond_to do |format|
        format.html { redirect_to @listing }
      end
    else
      respond_to do |format|
        format.html { render 'listings/show' }
      end
    end
  end
  
end

runner/benchmarks/rails/app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @listings = Listing.all
    
    respond_to do |format|
      format.html
      format.xml { render :xml => 
      @listings.to_xml(:include => [:user, :bids], :except => :image, :methods => :image_url) }
      format.json { render :json => @listings }
    end
  end
  
  def show
    @listing = Listing.find(params[:id])
    
    respond_to do |format|
      format.html
      format.xml { render :xml => 
      @listing.to_xml(:include => [:user, :bids], :except => :image, :methods => :image_url) }
      format.json { render :json => @listing }
    end
  end
  
  def new
    @listing = Listing.new
  end
  
  def create
    @listing = current_user.listings.build(params[:listing])
    
    if @listing.save
      redirect_to @listing
    else
      render 'new'
    end
  end
  
  def edit
    @listing = current_user.listings.find(params[:id])
  end
  
  def update
    @listing = current_user.listings.find(params[:id])
    if @listing.update_attributes(params[:listing])
      flash[:notice] = 'Listing updated.'
      redirect_to @listing
    else
      flash.now[:alert] = "There were problems saving."
      render 'edit'
    end
  end
  
  def destroy
    @listing = current_user.listings.find(params[:id])
    @listing.destroy
    redirect_to listings_path
  end
end

runner/benchmarks/rails/app/controllers/pids_controller.rb
class PidsController < ApplicationController
  def show
    render :text => Process.pid
  end
end

runner/benchmarks/rails/app/helpers/application_helper.rb
module ApplicationHelper
end

runner/benchmarks/rails/app/views/bids/_form.html.erb
<%= form_for [@listing, @bid || Bid.new] do |form| %>
	
	<% if form.object.errors.any? %>
    <div id="errorExplanation">
      <h4>The following errors prohibited this form from being saved:</h4>
      <ul>
        <% form.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<%= form.label :amount %>
	<%= form.text_field :amount, :size => 6 %>
	<%= form.submit "Bid" %>
<% end %>

runner/benchmarks/rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>eHarbor</title>
  <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
  <div id="main">
    <header>
      <div id="toolbar">
				<% if user_signed_in? %>
					Signed in as <%= link_to current_user.email, edit_user_registration_path %> |
					<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
				<% else %>
					<%= link_to "Sign In", new_user_session_path %> |
					<%= link_to "Register", new_user_registration_path %>
				<% end %>
      </div>
      <h1>
        <%= link_to '<span class="e1">e</span><span class="h2">H</span><span class="a3">a</span><span class="r4">r</span><span class="b5">b</span><span class="o6">o</span><span class="r7">r</span>'.html_safe, root_path %>
      </h1>
      <nav>
        <ul>
          <li><%= link_to "Buy", listings_path %></li>
          <li><%= link_to "Sell", new_listing_path %></li>
        </ul>
      </nav>
    </header>
    <% if notice %><p class="notice"><%= notice %></p><% end %>
    <% if alert %><p class="alert"><%= alert %></p><% end %>

    <%= yield %>
  </div>
</body>
</html>

runner/benchmarks/rails/app/views/listings/_form.html.erb
<%= form_for @listing, :html => {:multipart => true} do |form| %>
 	<% if @listing.errors.any? %>
    <div id="errorExplanation">
      <h2>The following errors prohibited this form from being saved:</h2>
      <ul>
        <% @listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
	
	<p>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</p>
	
	<p>
		<%= form.label :description %>
		<%= form.text_area :description %>
	</p>
	
	<p>
		<%= form.label :image %>
		<%= form.file_field :image %>
	</p>
	
	<p>
		<%= form.submit %>
	</p>
<% end %>

runner/benchmarks/rails/app/views/listings/_info.html.erb
<dl id="info" class="info">
	<dt>History:</dt>
	<dd><%= pluralize @listing.bids.count, 'bid' %></dd>
	
	<% if @listing.highest_bid %>
		<dt>Highest Bid:</dt>
		<dd><%= number_to_currency @listing.highest_bid.amount %></dd>
	<% end %>
</dl>

runner/benchmarks/rails/app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= render 'form' %>

runner/benchmarks/rails/app/views/listings/index.html.erb
<h1><%= pluralize @listings.size, 'listing' %></h1>

<%= link_to 'New Listing', new_listing_path %>

<ul>
	<% @listings.each do |listing| %>
		<li><%= link_to listing.title, listing %></li>
	<% end %>
</ul>

runner/benchmarks/rails/app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

runner/benchmarks/rails/app/views/listings/show.html.erb
<h1><%= @listing.title %></h1>

<%= render 'listings/info' %>

<p>Posted: <%= time_ago_in_words @listing.created_at %> ago</p>

<div>
	<%= image_tag @listing.image_url if @listing.image.present? %>
	
	<%= simple_format auto_link(@listing.description)  %>
</div>

<div id="bid">
	<h3>Place a bid</h3>
	<%= render 'bids/form' %>
</div>

<%= link_to 'Back', listings_path %>
<%= link_to 'JSON', listing_path(@listing, :format => :json) %>

<% if @listing.user == current_user %>
	<%= link_to 'Edit', edit_listing_path(@listing) %>
	<%= link_to 'Delete', @listing, :method => :delete %>
<% end %>